import type { GameProfile } from "./types";

export const GAME_PRESETS: GameProfile[] = [
  {
    id: "pubgm",
    name: "PUBG Mobile / BGMI",
    category: "Battle Royale",
    hdTier: 3,
    gpuBound: 0.55,
    cpuBound: 0.45,
    ramNeedGb: 4,
    thermalLoad: 0.85,
    tips: [
      "Smooth + Extreme FPS uses the least GPU headroom — cap there if thermals throttle you",
      "Turn Anti-Aliasing OFF; on mobile GPUs it costs ~8-12% fps for near-zero visual gain",
      "In-game 'Gfx Tool' style render-scale tricks get flagged on some anti-cheats — use official settings only",
      "Disable 'Auto-adjust graphics' — it silently drops resolution mid-fight",
    ],
  },
  {
    id: "codm",
    name: "Call of Duty: Mobile",
    category: "FPS",
    hdTier: 3,
    gpuBound: 0.6,
    cpuBound: 0.4,
    ramNeedGb: 4,
    thermalLoad: 0.9,
    tips: [
      "Very High frame rate + Medium graphics beats Max graphics + Medium frame rate in every scenario",
      "Turn off 'Real-time shadows' — single biggest fps sink on this title",
      "120fps mode needs the phone cool: run your scan, then clear background apps before matches",
    ],
  },
  {
    id: "mlbb",
    name: "Mobile Legends: Bang Bang",
    category: "MOBA",
    hdTier: 2,
    gpuBound: 0.35,
    cpuBound: 0.65,
    ramNeedGb: 3,
    thermalLoad: 0.5,
    tips: [
      "This game is CPU-bound — background apps hurt it more than graphics settings do",
      "Enable 'High FPS mode' in settings; most phones hide it behind Advanced",
      "Turn off custom skin animations in competitive modes",
    ],
  },
  {
    id: "genshin",
    name: "Genshin Impact / Wuthering Waves",
    category: "Open World HD",
    hdTier: 5,
    gpuBound: 0.8,
    cpuBound: 0.2,
    ramNeedGb: 6,
    thermalLoad: 1.0,
    tips: [
      "30fps locked looks better than a dropping 45 — pick one and cap it",
      "Render resolution 0.8 saves ~20% GPU with barely visible difference",
      "Sustained play > 20 min WILL throttle on most phones — a cheap cooler is the real fix",
      "Bloom + motion blur off recovers ~6% fps",
    ],
  },
  {
    id: "ff",
    name: "Free Fire",
    category: "Battle Royale",
    hdTier: 1,
    gpuBound: 0.3,
    cpuBound: 0.7,
    ramNeedGb: 2,
    thermalLoad: 0.4,
    tips: [
      "Runs on anything — if it lags, it's RAM or background apps, 100%",
      "Use 'Standard' graphics with High FPS for the competitive edge",
    ],
  },
  {
    id: "wr",
    name: "Wild Rift",
    category: "MOBA",
    hdTier: 2,
    gpuBound: 0.45,
    cpuBound: 0.55,
    ramNeedGb: 3,
    thermalLoad: 0.55,
    tips: [
      "Cap at 60fps; the game's netcode adds no advantage above that",
      "Device-level 'Performance mode' + 60fps cap stays stable in 5v5 late game",
    ],
  },
  {
    id: "rdr2",
    name: "HD Ports (GTA SA DE, RDR ports, emulators)",
    category: "HD / Emulated",
    hdTier: 5,
    gpuBound: 0.7,
    cpuBound: 0.3,
    ramNeedGb: 8,
    thermalLoad: 1.0,
    tips: [
      "Emulators live and die on single-core speed — check your single-core score above",
      "Cap emulated games at 30/60 exactly; frame pacing issues cause fake 'lag'",
      "Vulkan backend in emulators beats OpenGL on nearly all Adreno and Mali GPUs",
    ],
  },
];
